name: dadata_suggestions
description: Dadata address suggestions (including forward and reverse geocoding) for Flutter.
version: 0.1.3
repository: https://github.com/illabo/dadata_suggestions

environment:
  sdk: ^3.4.0
  flutter: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.6.0
  http: ^1.2.2
  retrofit: 4.0.3
  frontend_server_client: ^4.0.0
  dio: ^5.7.0

dev_dependencies:
  build_runner: ^2.4.13
  json_serializable: ^6.6.0
  retrofit_generator: 8.0.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
