// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'suggestion_data.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

SuggestionData _$SuggestionDataFromJson(Map<String, dynamic> json) =>
    SuggestionData(
      json['postal_code'] as String?,
      json['country'] as String?,
      json['country_iso_code'] as String?,
      json['federal_district'] as String?,
      json['region_fias_id'] as String?,
      json['region_kladr_id'] as String?,
      json['region_iso_code'] as String?,
      json['region_with_type'] as String?,
      json['region_type'] as String?,
      json['region_type_full'] as String?,
      json['region'] as String?,
      json['area_fias_id'] as String?,
      json['area_kladr_id'] as String?,
      json['area_with_type'] as String?,
      json['area_type'] as String?,
      json['area_type_full'] as String?,
      json['area'] as String?,
      json['city_fias_id'] as String?,
      json['city_kladr_id'] as String?,
      json['city_with_type'] as String?,
      json['city_type'] as String?,
      json['city_type_full'] as String?,
      json['city'] as String?,
      json['city_area'] as String?,
      json['city_district_fias_id'] as String?,
      json['city_district_kladr_id'] as String?,
      json['city_district_with_type'] as String?,
      json['city_district_type'] as String?,
      json['city_district_type_full'] as String?,
      json['city_district'] as String?,
      json['settlement_fias_id'] as String?,
      json['settlement_kladr_id'] as String?,
      json['settlement_with_type'] as String?,
      json['settlement_type'] as String?,
      json['settlement_type_full'] as String?,
      json['settlement'] as String?,
      json['street_fias_id'] as String?,
      json['street_kladr_id'] as String?,
      json['street_with_type'] as String?,
      json['street_type'] as String?,
      json['street_type_full'] as String?,
      json['street'] as String?,
      json['house_fias_id'] as String?,
      json['house_kladr_id'] as String?,
      json['house_type'] as String?,
      json['house_type_full'] as String?,
      json['house'] as String?,
      json['block_type'] as String?,
      json['block_type_full'] as String?,
      json['block'] as String?,
      json['flat_fias_id'] as String?,
      json['flat_type'] as String?,
      json['flat_type_full'] as String?,
      json['flat'] as String?,
      json['flat_area'] as String?,
      json['square_meter_price'] as String?,
      json['flat_price'] as String?,
      json['postal_box'] as String?,
      json['fias_id'] as String?,
      json['fias_code'] as String?,
      json['fias_level'] as String?,
      json['fias_actuality_state'] as String?,
      json['kladr_id'] as String?,
      json['geoname_id'] as String?,
      json['capital_marker'] as String?,
      json['okato'] as String?,
      json['oktmo'] as String?,
      json['tax_office'] as String?,
      json['tax_office_legal'] as String?,
      json['timezone'] as String?,
      json['geo_lat'],
      json['geo_lon'],
      json['beltway_hit'] as String?,
      json['beltway_distance'] as String?,
      json['metro'] as List<dynamic>?,
      json['qc'],
      json['qc_geo'],
      json['qc_complete'],
      json['qc_house'],
      (json['history_values'] as List<dynamic>?)
          ?.map((e) => e as String)
          .toList(),
      json['unparsed_parts'] as String?,
      json['source'] as String?,
    );

Map<String, dynamic> _$SuggestionDataToJson(SuggestionData instance) =>
    <String, dynamic>{
      'postal_code': instance.postalCode,
      'country': instance.country,
      'country_iso_code': instance.countryIsoCode,
      'federal_district': instance.federalDistrict,
      'region_fias_id': instance.regionFiasId,
      'region_kladr_id': instance.regionKladrId,
      'region_iso_code': instance.regionIsoCode,
      'region_with_type': instance.regionWithType,
      'region_type': instance.regionType,
      'region_type_full': instance.regionTypeFull,
      'region': instance.region,
      'area_fias_id': instance.areaFiasId,
      'area_kladr_id': instance.areaKladrId,
      'area_with_type': instance.areaWithType,
      'area_type': instance.areaType,
      'area_type_full': instance.areaTypeFull,
      'area': instance.area,
      'city_fias_id': instance.cityFiasId,
      'city_kladr_id': instance.cityKladrId,
      'city_with_type': instance.cityWithType,
      'city_type': instance.cityType,
      'city_type_full': instance.cityTypeFull,
      'city': instance.city,
      'city_area': instance.cityArea,
      'city_district_fias_id': instance.cityDistrictFiasId,
      'city_district_kladr_id': instance.cityDistrictKladrId,
      'city_district_with_type': instance.cityDistrictWithType,
      'city_district_type': instance.cityDistrictType,
      'city_district_type_full': instance.cityDistrictTypeFull,
      'city_district': instance.cityDistrict,
      'settlement_fias_id': instance.settlementFiasId,
      'settlement_kladr_id': instance.settlementKladrId,
      'settlement_with_type': instance.settlementWithType,
      'settlement_type': instance.settlementType,
      'settlement_type_full': instance.settlementTypeFull,
      'settlement': instance.settlement,
      'street_fias_id': instance.streetFiasId,
      'street_kladr_id': instance.streetKladrId,
      'street_with_type': instance.streetWithType,
      'street_type': instance.streetType,
      'street_type_full': instance.streetTypeFull,
      'street': instance.street,
      'house_fias_id': instance.houseFiasId,
      'house_kladr_id': instance.houseKladrId,
      'house_type': instance.houseType,
      'house_type_full': instance.houseTypeFull,
      'house': instance.house,
      'block_type': instance.blockType,
      'block_type_full': instance.blockTypeFull,
      'block': instance.block,
      'flat_fias_id': instance.flatFiasId,
      'flat_type': instance.flatType,
      'flat_type_full': instance.flatTypeFull,
      'flat': instance.flat,
      'flat_area': instance.flatArea,
      'square_meter_price': instance.squareMeterPrice,
      'flat_price': instance.flatPrice,
      'postal_box': instance.postalBox,
      'fias_id': instance.fiasId,
      'fias_code': instance.fiasCode,
      'fias_level': instance.fiasLevel,
      'fias_actuality_state': instance.fiasActualityState,
      'kladr_id': instance.kladrId,
      'geoname_id': instance.geonameId,
      'capital_marker': instance.capitalMarker,
      'okato': instance.okato,
      'oktmo': instance.oktmo,
      'tax_office': instance.taxOffice,
      'tax_office_legal': instance.taxOfficeLegal,
      'timezone': instance.timezone,
      'geo_lat': instance.geoLat,
      'geo_lon': instance.geoLon,
      'beltway_hit': instance.beltwayHit,
      'beltway_distance': instance.beltwayDistance,
      'metro': instance.metro,
      'qc': instance.qc,
      'qc_geo': instance.qcGeo,
      'qc_complete': instance.qcComplete,
      'qc_house': instance.qcHouse,
      'history_values': instance.historyValues,
      'unparsed_parts': instance.unparsedParts,
      'source': instance.source,
    };
